version: '3'
services:
  app:
    build:
      context: .
# =========ローカルと本番切り替え===========
    command: bundle exec puma -C config/puma.rb -e production
    # command: bundle exec puma -C config/puma.rb
# ======================================
    volumes:
      - .:/study_app_aws
      - public-data:/study_app_aws/public
      - tmp-data:/study_app_aws/tmp
      - log-data:/study_app_aws/log
    networks:
      - study_app_aws-network
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub" # 追記
    depends_on:
      - db
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest # 追記
    ports:
      - 4444:4444
  #


  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: study_app_aws_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - study_app_aws-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/study_app_aws/public
      - tmp-data:/study_app_aws/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - study_app_aws-network



volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  study_app_aws-network:
    external: true