default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
# PasswordとUsernameはdocker-compose.ymlと合わせます
  username: root
  password: password
  host: db

development:
  <<: *default
  database: study_app_aws_development

test:
  <<: *default
  database: study_app_aws_test

# production:
#   <<: *default
#   database: <%= ENV['DB_DATABASE'] %>
#   adapter: mysql2
#   encoding: utf8mb4
#   charset: utf8mb4
#   collation: utf8mb4_general_ci
#   host: <%= ENV['DB_HOST'] %>
#   username: <%= ENV['DB_USERNAME'] %>
#   password: <%= ENV['DB_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see Rails configuration guide
  # https://railsguides.jp/configuring.html#データベース接続をプールする
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: study_app_heroku_production
  username: study_app_heroku
  password: <%= ENV['STUDY_APP_HEROKU_DATABASE_PASSWORD'] %>